name: Rust Cross-Compile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            use-cross: true
          - target: aarch64-unknown-linux-musl
            use-cross: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Rust toolchain
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      # Install dependencies for cross compilation
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config musl-tools

      # For musl targets, build with RUSTFLAGS to statically link C libraries
      - name: Build musl targets
        if: matrix.use-cross
        run: |
          # Build with static linking for musl
          cargo build --release --target ${{ matrix.target }}
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
          CARGO_TERM_COLOR: always
          # Force static linking of C libraries
          RUSTFLAGS: "-C target-feature=+crt-static"
          # Tell OpenSSL to compile in vendored mode
          OPENSSL_STATIC: 1
          OPENSSL_NO_VENDOR: 0

      # For Windows target, build normally
      - name: Build Windows target
        if: "!matrix.use-cross"
        run: cargo build --release --target ${{ matrix.target }}

      # Upload the compiled binaries
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/